document.getElementById("info1").onclick=function(){
    document.getElementById("sidebar").innerHTML=" Sinopsis: Gags es un hombre que se viste de payaso y persigue a las personas acompañado de un puñado de globos de color negro. La historia muestra un cruce de historias en las que Gags consigue asesinar a varias personas. <br> Crítica: Lo anterior resulta en que si bien Gags tiene un aspecto terrorífico, al momento de desarrollarse la trama termina en ser una grabación larguísima del payaso apareciendo en distintos puntos de la ciudad. De hecho, más que asustar, Gags parece un tipo inofensivo que podrías pensar que sólo está ahí, parado, para pedir dinero o a lo mejor está realizando algún performance. Esta basura sólo es superada por las actuaciones de quienes participan ahí. Todo en conjunto es el gran ácido que dañará tus ojos, ya que está hilado por un ritmo apabullante que resulta ser una verdadera tortura, una experiencia desagradable y una pérdida de tiempo real."
}

document.getElementById("info2").onclick=function(){
    document.getElementById("sidebar").innerHTML=" Sinopsis: “El visitante”, nuevo largometraje del director boliviano Martín Boulocq, es un brillante estudio de la creciente popularidad de la Iglesia Evangélica en Latinoamérica y su influencia manipulativa en personas vulnerables, todo aplicado a la historia de un padre intentando conectar con su hija. Este es un elegante análisis del poder nocivo de la Iglesia Evangélica en Bolivia y el resto de Latinoamérica. Boulocq crea humanidad y calidez a través de una historia de redención involucrando a un padre intentando salvar a su hija, para luego hacerte sentir la devastación manipuladora que los tentáculos evangélicos ejercen en su población vulnerable. <br> Critica: The Visitor frecuenta demasiados caminos trillados y tiene escenas de terror familiares. La historia avanza a veces demasiado lenta y, en muchas ocasiones, demasiado televisiva."
}

document.getElementById("info3").onclick=function()
{
    document.getElementById("sidebar").innerHTML="Sinopsis: La detective Amelia Van Helsing está a la caza desesperada del asesino, responsable de una serie de asesinatos espeluznantes dirigidos contra jóvenes mujeres. Las cosas solo empeoran cuando todas las evidencias apuntan al aparentemente intocable Conde Drácula. Pero cuando la novia de Van Helsing desaparece, se ve obligada a cuestionar la existencia misma de los vampiros. <br> Critica: El gran problema es que el casting de los actores fue pobre y así tenemos a un debutante, Jack Herbert, interpretando a Drácula, un papel que requiere muchas tablas para interpretarlo de manera fresca, algo en lo que el joven actor falla estrepitosamente. El giro final no es tan sorpresivo tampoco y el enfrentamiento cumbre entre nuestros héroes y el vampiro no está a la altura que se hubiera deseado. Pero no todo es tan malo. Como apuntamos, el hecho de buscar una ciudad europea para la filmación le da una atmósfera gótica aceptable. "
}


